/*
 Generated by typeshare 1.13.2
*/

export interface BoardListResponse {
	title: string;
	content: string;
	name: string;
	user_id: number;
}

export interface BoardRequest {
	title?: string;
	content?: string;
	name: string;
	user_id?: number;
}

export interface KakaoResponse {
	id: number;
	connected_at: string;
}

export interface KakaoTokenResponse {
	nickname: string;
	profile_image?: string;
	thumbnail_image: string;
}

export interface LoginRequest {
	access_token: string;
	refresh_token: string;
}

export interface UserDto {
	name: string;
	email?: string;
	profile_image?: string;
	age?: number;
	gender?: string;
}

