import FooterComponent from "@/components/Footer/footer";
import HeaderComponent from "@/components/Header/header";
import type { Metadata } from "next";
import "./globals.css";
import styles from "./style.module.css";
import { QueryProvider } from "@/hooks/provider";

export const metadata: Metadata = {
  title: "Pet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <QueryProvider>
        <body className={`antialiased ${styles.outer}`}>
          <div className="font-custom">
            <HeaderComponent />
            <div className={styles.container}>{children}</div>
            <FooterComponent />
          </div>
        </body>
      </QueryProvider>
    </html>
  );
}
