export const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
export const KAKAO_REST_API_KEY = process.env.NEXT_PUBLIC_KAKAO_RESTAPI_KEY;
export const KAKAO_REDIRECT_URI = process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI;
export const FRONT_URL = process.env.NEXT_PUBLIC_FRONTEND_URL;